### ISSUE TITLE
PetriFunctor Design

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/AlgebraicPetri.jl#1]
For the design of the PetriFunctors, I think we want to have something like the following:

```julia
abstract AbstractFunctor end # this type should be imported from Catlab.
abstract AbstractLaxitor end # this type should be imported from Catlab.

struct PetriDecorator <: AbstractFunctor end

struct PetriLaxitor <: AbstractLaxitor end

struct LaxMonoidalFunctor{Ftr, Lxr} <: AbstractFunctor 
  F::Ftr
  L::Lxr
end

D = LaxMonoidal(PetriDecorator(), PetriLaxitor())

"""we follow FinOrd's lead in taking the skeleton of FinSet so we work with Petri nets 
where the state space is a single Int n rather than the range 1:n.
A functor from FinOrd to Set has an objects part, which given an object n in FinOrd 
(a natural number) should return a representation of F(n)::Set, sets can be represented as
a predicate that takes an element and returns true if the element is in the set. Here we take
any julia value and test whether it is a Petri net on n states.
"""
function (pd::PetriDecorator)(n::FinOrdOb) begin
   return p -> typeof(p) == Petri.Model && (p.S == n)
end

"""mapping a FinOrdFunc over the transitions of a Petri net means renumbering the states 
incident to a transition where the transitions of a petri net are stored as a list of tuples of lists. 
This could be easily adapted for storing transitions in a list of pairs of multisets.
"""
map(f::Function, ts::Vector{Tuple{Vector{Int}, Vector{Int}}) = [(f.(t[1]), f.(t[2])) for t in ts]

"""
A functor from FinOrd to Set has a hom part, which given a hom f in FinOrd 
(a function n::Int->m::Int) should return a representation of F(f)::F(n)->F(m), 
here we implement this as a function that takes a Petri net of size n to a Petri net of size m,
such that the transitions are mapped appropriately.
"""
function (pd::PetriDecorator)(f::FinOrdFunc)
  return (p::Petri.Model) -> Petri.Model(codom(f), map(f, p.Δ))
end

"""the laxitor takes a pair of decorations and returns the coproduct decoration. For Petri nets, it encodes
the idea that you shift the states of q up by the number of states in p.
"""
(l::PetriLaxitor)(p::Petri.Model, q::Petri.Model) = Petri.Model(p.S+q.S, hcat(p.Δ, map(x->x+p.S, q.Δ)))
```

Then the compose/otimes operation for petri decorated cospans can be implemented in terms of these functions and the universal contructions in `catlab.categorical_algebra`. We use the empty structs because there is no information in the functor here it just tells us how we want to lift `FinOrdOb`s and `FinOrdFunc`s up to functions that operate on `Petri.Model`s. 

Once we implement the C-Set approach, the definitions of the `function (pd::PetriDecorator)(f::FinOrdFunc)` and `(l::PetriLaxitor)(p::Petri.Model, q::Petri.Model)` can be inferred from the definition of C-Sets, but for now we code it up manually as part of the "code that understands math" aspect of partially symbolic computing.

**Comment by jpfairbanks** [comment]
I think the constructions for the composite decoration can be found from these diagrams.

The composition of the cospans is labeled like this,
![image](https://user-images.githubusercontent.com/2753998/86196469-57d34580-bb21-11ea-9e60-ba763ab38345.png)

Then the composition of the decorations must satisfy:

![image](https://user-images.githubusercontent.com/2753998/86197226-f318ea80-bb22-11ea-81af-e66971fef7bb.png)

Where we can treat FA ⊔ FB ≃ F(A ⊔ B) because of the laxitor that combines two Petri nets into one by shifting the states of the second one.

**Comment by mehalter** [comment]
This is great and really helped with the implementation of `otimes` and `compose` of `PetriCospans`!
