### ISSUE TITLE
`mca` not searching in order of size

### ISSUE THREAD

**Issue by p-stokes** [AlgebraicJulia/AlgebraicPetri.jl#128]
`mca` currently searches by taking the list of subACSets formed by removing a single part from each object of the smaller input ACSet. It then looks for a mono from each subACSet in the list into the larger input ACSet. If it finds any monos, it returns the largest ones, otherwise it recurses on the list of subACSets.

Unfortunately, at each round the subACSets in the list can be of varying size, and if it finds a mono for one of the smaller subACSets, it will terminate without further searching the larger subACSets.
 
For example, in the following `mca` returns the four separate nodes, rather than a vector of isomorphic cases of the single transition with a single input and single output. 
```
m3 = LabelledPetriNet(
  [:X,:Y,:W,:Z],
  :f=>(:X=>(:W, :Y, :Z))
)
m4 = LabelledPetriNet(
  [:X,:W,:Y,:Z],
  :f=>((:W, :X, :Y)=>:Z)
)
test = mca(m3,m4)
```

**Comment by jpfairbanks** [comment]
Would a good fix be to sort the list of subacsets by size at each level of the recursion?

**Comment by p-stokes** [comment]
That's part of it. But I think it shouldn't be recursing by levels at all. What I'm thinking is there should just be a heap of subacsets that's recursed over. At each recursion, the largest subacset is checked. If it's smaller than the current mca's, then stop. If larger or equal to the mca's: 
  pop it from the heap.
  if it has a mono, add it to the list of mca's.
  else, get it's subacsets and add them to the heap.
  recur over the updated heap.

I might add some arguments to set size limits as well. 

I'm currently implementing it this way, but let me know if you see a better way, especially with time/space considerations.

**Comment by p-stokes** [comment]
> Would a good fix be to sort the list of subacsets by size at each level of the recursion?

That's part of it. But I think it shouldn't be recursing by levels at all. What I'm thinking is there should just be a heap of subacsets that's recursed over. At each recursion, the largest subacset is checked. If it's smaller than the current mca's, then stop. If larger or equal to the mca's: 
- pop it from the heap.
- if it has a mono, add it to the list of mca's.
- else, get it's subacsets and add them to the heap.
- recur over the updated heap.

I might add some arguments to set size limits as well. 

I'm currently implementing it this way, but let me know if you see a better way, especially with time/space considerations.
