### ISSUE TITLE
Is there a function already to generate Petri.Model from LabelledPetriNet?

### ISSUE THREAD

**Issue by sdwfrost** [AlgebraicJulia/AlgebraicPetri.jl#177]
As it says in the title, I have a problem where I want to convert a LabelledPetriNet to Petri.Model - I couldn't seem to find any conversion code - am I missing something?

**Comment by mehalter** [comment]
Do you mean integration with Petri.jl? I believe all integration with Petri.jl was removed because this package really just supercedes it. It supports all of the features that are in Petri.jl

**Comment by sdwfrost** [comment]
I wanted to generate SDEs and jump processes as well as the vector field; I didn't see this functionality in AlgebraicPetri.jl

**Comment by sdwfrost** [comment]
(I also want to add in a conversion to a discrete-time stochastic solver along the same lines of [Gemlib](https://gem-epidemics.gitlab.io/practical-epidemics/iddinf/02_intro_to_gemlib.html)). I suspect that I'll have to extend the model specification to split out discrete and continuous states, so I can lower to a PDMP https://docs.sciml.ai/JumpProcesses/stable/tutorials/jump_diffusion/)

**Comment by slwu89** [comment]
@sdwfrost you're right, the only simulation functionality available "natively" in AlgPetri right now is the ODE interpretation of the Petri net, as seen in these two functions for the vector field: https://github.com/AlgebraicJulia/AlgebraicPetri.jl/blob/df03fc630f4246cc121435de831230feee7adafd/src/AlgebraicPetri.jl#L283-L396

I wrote the `vectorfield_expr` method with the intention of putting in a CTMC interpretation as well, but alas did not get around to it. But the logic is there, see the comments in the code, referring to "firing intensity" = )
