### ISSUE TITLE
Forgotten Exponential?

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/AlgebraicPetri.jl#33]
I feel like there should be an `exp` here, am I missing something? https://github.com/AlgebraicJulia/AlgebraicPetri.jl/blob/8c664224b551f4cf32bd70249be4ab64bae9a76a/src/AlgebraicPetri.jl#L137

Ah, the real problem is that they should no longer be called log_rates.

**Comment by jpfairbanks** [comment]
Yeah, we tried to solve in log-space for stability, but ran into problems and reversed course. Any input on making this code more stable would be well received.

**Comment by olynch** [comment]
This wouldn't necessarily make this more stable, but would we get a speedup if we code-genned this, to remove all allocations and loops?

**Comment by jpfairbanks** [comment]
That would be useful as an additional functionality. If you have one big Petri net with many parameters, you want to compile it. If you are doing model selection over many small nets, you want to interpret them.

**Comment by mehalter** [comment]
Resolved with #107
