### ISSUE TITLE
Potential Catalyst Breaking Update

### ISSUE THREAD

**Issue by bosonbaas** [AlgebraicJulia/AlgebraicPetri.jl#62]
With the update of Catalyst.jl from 6.13 to 6.14, it appears that using arrays to index symbol arrays is no longer supported. This breaks the CatalystInterop tooling.

**Comment by bosonbaas** [comment]
I'll work on updating our tooling to the supported interface.

**Comment by mehalter** [comment]
Does Julia require semantic versioning to be followed? If so, we should let the Catalyst people know that they have a breaking minor update

**Comment by bosonbaas** [comment]
I have an issue filed with Catalyst at https://github.com/SciML/Catalyst.jl/issues/350 which discusses a similar problem (exposed by some documentation code). A resolution to that issue should either show the breaking change, or provide us with the proper method for indexing symbol arrays.

**Comment by mehalter** [comment]
The resolution to the issue is to tag breaking changes with major version releases.

**Comment by isaacsas** [comment]
CC: @ Chrisrackauckas: It seems like ModelingToolkit did not make a new major release when switching to array variables? (Which may be why Catalyst only has received minor version bumps since nothing major has changed in the package, only the dependencies…)

**Comment by ChrisRackauckas** [comment]
Yes, I've mentioned this to @shashi and @yingboma

**Comment by mehalter** [comment]
Fixed with #63
