### ISSUE TITLE
SDE version of Petri Semantics

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/AlgebraicPetri.jl#7]
It would be awesome to have an SDE model of PetriNets with the interface

```julia
pn = Petri.Model(...)
p, cb = SDEProblem(pn, u0, params, tspan)
solve(p, callback=cb)
```

**Comment by mehalter** [comment]
Could we move this issue to Petri.jl?

**Comment by mehalter** [comment]
Moved to https://github.com/mehalter/Petri.jl/issues/22
