### ISSUE TITLE
Type piracy in visualization functions

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/AlgebraicPetri.jl#73]
The visualization module has lots of [type piracies](https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy). For example, the `Graph` constructor is defined for `Multispan`, `Subobject`, and `ACSetTransformation`, but AlgebraicPetri doesn't own any of these types, nor are the methods defined here general enough for those types.

**Comment by mehalter** [comment]
I think this has been resolved in the latest version of AlgebraicPetri. Let me know if I'm mistaken and I can reopen this!
