### ISSUE TITLE
Inefficiency in `vectorfield` function

### ISSUE THREAD

**Issue by bosonbaas** [AlgebraicJulia/AlgebraicPetri.jl#77]
The `vectorfield` function currently iterates through each element of the transition matrix, making each evaluation be O(ST) for number of states S and number of transitions T. This can cause significant slowdown on large sparse PetriNets, and could be improved by using a sparse representation of the transition matrix.

**Comment by epatters** [comment]
Do we even need the transition matrix to generate the vector field? Seems like we could just use the acset data structure to read off the needed information.

**Comment by bosonbaas** [comment]
Yeah, I agree that'd be the most efficient way to do it.

**Comment by slwu89** [comment]
I think this can be closed based on #107?

**Comment by mehalter** [comment]
Yeah this can be closed now :)
