### ISSUE TITLE
ReactionNet documentation example

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/AlgebraicPetri.jl#78]
the SIR example construction in the docstring for `LabelledReactionNet` errors for me.
```julia
ReactionNet{Float64, Float64}([:S=>10,:I=>1,:R=>0],
    (:inf=>0.5)=>((1,2)=>(2,2)),
    (:rec=>0.1)=>(2=>3))

ERROR: MethodError: Cannot `convert` an object of type Pair{Symbol, Int64} to an object of type Float64
```
All the other code examples in `AlgebraicPetri.jl` work for me, though, as well as the SIR example from the tests:

```julia
LabelledReactionNet{Float64, Float64}([:S=>1.0, :I=>0.0, :R=>0.0],
    (:inf=>0.5)=>((:S,:I)=>(:I,:I)),
    (:rec=>0.1)=>(:I=>:R))
```

**Comment by jpfairbanks** [comment]
It looks like we used to support named states but then specifying the input and output relations with their Id numbers. This is probably a transient state between no support for labels and full support for labels. I don't know if we want to support this mixed us case anymore in which case we should just update the doc string to use the labels for I and O.
