### ISSUE TITLE
naive questions on removing edges and states

### ISSUE THREAD

**Issue by anandijain** [AlgebraicJulia/AlgebraicPetri.jl#93]
i am in the process of reading through the RxNet paper (i don't really know CT)

right now, im just recreating tons and tons of petri nets with one or two edges different and its starting to get cumbersome.
i wrote two helpers that made it easy to add transitions and get out the `(n, ts)` tuple used to construct the LabelledPetriNet

one problem i kept running into was not being able to easily remove edges/states. 
maybe it doesn't fit Catlabs philosophy or something, but my thought was, if we are creating sets of models to compare, it would be nice to "only store the diff", instead of lugging around a bunch of copies. in the example below, i wanted to start from the most basic SIR model and progressively work up to SEIRHD. im able to get part of the way there but I didn't see anything related to deleting transitions and species. id love some help on this.

at some point, i want to build some tools to be able to ask questions like "compare the death counts of all the models that take `:mutation => (:R=>:S)` into account"

thanks for the amazing package!

```julia
function add_things!(p::AbstractLabelledPetriNet, ts::Vararg{Union{Pair,Tuple}})
    n = snames(p)
    state_idx = AlgebraicPetri.state_dict(n)
    for (name, (ins, outs)) in ts
        i = add_transition!(p, tname=name)
        ins = AlgebraicPetri.vectorify(ins)
        outs = AlgebraicPetri.vectorify(outs)
        add_inputs!(p, length(ins), repeat([i], length(ins)),
            map(x -> state_idx[x], collect(ins)))
        add_outputs!(p, length(outs), repeat([i], length(outs)),
            map(x -> state_idx[x], collect(outs)))
    end
    p
end

function get_things(p)
    is_ = inputs.((p,), 1:nt(p))
    os_ = outputs.((p,), 1:nt(p))
    tns = tnames(p)
    sns = snames(p)
    (sns, [tns[i] => (sns[is_[i]] => sns[os_[i]]) for i in 1:nt(p)])
end

sir_n = [:S, :I, :R]
sir_t = [:exp => ((:S, :I) => (:I, :I)), :rec => (:I => :R)]
sir = LabelledPetriNet(
    sir_n, sir_t...
)

sird = deepcopy(sir)
add_species!(sird; sname=:D)
@test has_species(sird, :D)
add_things!(sird, :death => (:I => :D))

n, ts = get_things(sird)
@test LabelledPetriNet(n, ts...) == sird

# how do i split I into I and E? 
seird = LabelledPetriNet(
    [:S, :E, :I, :R, :D],
    :exp => ([:S, :I] => [:E, :I]),
    :conv => (:E => :I),
    :rec => (:I => :R),
    :death => (:I => :D)
)
```

**Comment by jpfairbanks** [comment]
You can use `rem_parts!` from the Catlab.CategoricalAlgebra module to delete stuff. Comparing models with `homomorphisms` from Catlab is also productive. That will give you all the Petri net Homomorphisms between your two models. To compare models you probably actually want to compute a maximumal common submodel, which is a feature that we don't support quite yet.

**Comment by anandijain** [comment]
thanks james! ill play around with that. it seems like something like `add_inputs!` that could have a wrapper function around `rem_parts` for AlgebraicPetri.

i have been thinking about writing a library that has some syntax for defining and applying rules to graphs (or maybe categories?), which could easily act on petri nets (i think).

for example, the `insert_before` rule would be `{{xs__, y}} -> {{xs, z}, {z, y}}` which would match all `inneighbors(y)`, plug them into a new vertex z, then connect z to y, leaving `outneighbors(y)` unchanged.

then i'd `apply_rule(g, rule, vertex)` or something to attempt a match + apply on a specific vertex, or `apply_rule(g, rule)` and apply on all vertices.

one extension of this that would be particularly useful is predicated rules like `{{y, xs__}} -> {{y, xs/;P1}, {y, z}, {z, xs/;P2}}`
which would allow me to wire based on properties of the matched vertices.

this would allow me to easily describe common model modifications that i may want (ie splitting infected to exposed and infected)

im coming from Graphs.jl, but i get the sense that catlab is the right way to define and express this.

**Comment by jpfairbanks** [comment]
You should look at AlgebraicRewriting.jl. @kris-brown and I have a paper about rewriting on generic combinatorial datastructures that is based on some Graph Transformation literature.

**Comment by slwu89** [comment]
@anandijain you might also find https://github.com/AlgebraicJulia/Structured-Epidemic-Modeling useful, which contains the examples from the paper https://royalsocietypublishing.org/doi/10.1098/rsta.2021.0309. You can build up complex Petri nets from smaller "atomic" building blocks that represent simpler dynamics (e.g. recovery, death, infection).

**Comment by mehalter** [comment]
I believe this has been resolved with a new Catlab feature with `cascading_rem_part!` and `cascading_rem_parts!`. This will delete a part of the C-Set and cascade to remove all references to that part as well!

Here is an example:

```julia
using AlgebraicPetri
using Catlab.CategoricalAlgebra

# Define a petri net
sir_petri = PetriNet(3, ((1, 2), (2, 2)), (2, 3))

# Delete transitions 1 and 2
cascading_rem_parts!(sir_petri, :T, [1,2])

# Delete state 1
cascading_rem_part!(sir_petri, :S, 1)
```
